"""add_session_id_to_search_logs

Revision ID: e7e9f9ab3035
Revises: d6e7f8a9b0c1
Create Date: 2026-03-22 19:59:49.682798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7e9f9ab3035'
down_revision: Union[str, Sequence[str], None] = 'd6e7f8a9b0c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_ingest_jobs_client_status'), table_name='ingest_jobs')
    op.add_column('search_logs', sa.Column('session_id', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_search_logs_client_created'), table_name='search_logs')
    op.drop_index(op.f('ix_search_logs_client_query'), table_name='search_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_search_logs_client_query'), 'search_logs', ['client_id', 'query'], unique=False)
    op.create_index(op.f('ix_search_logs_client_created'), 'search_logs', ['client_id', 'created_at'], unique=False)
    op.drop_column('search_logs', 'session_id')
    op.create_index(op.f('ix_ingest_jobs_client_status'), 'ingest_jobs', ['client_id', 'status'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=False)
    # ### end Alembic commands ###
